### ISSUE TITLE
Wrong RGBD images

### ISSUE THREAD

**Issue by ghx0x0** [ensenso/nxlib-python-interface#10] opened 2021-04-02 10:07 UTC
hello,
        thanks for the python version code for ensenso cams.
        I calibrated an IDS mono camera and a N35 stereo camera, then  use the this tool to fetch RGBD images, but the images get from [render point map] and [render point map texture] node seems wrong.
        Images list below（left:color   right: depth）:
             
![ensenso_color](https://user-images.githubusercontent.com/9670915/113406502-28b67100-93de-11eb-8ba7-55af1b5ab21d.png)

![ensenso_depth](https://user-images.githubusercontent.com/9670915/113406510-2d7b2500-93de-11eb-928b-9bb186e6ebf2.png)

        My py3 code list below:
               
![ensenso_code](https://user-images.githubusercontent.com/9670915/113406543-39ff7d80-93de-11eb-9438-b4fc11c5568e.png)

    
        I  can confirm that both cameras parameter files are loaded successfully and are right, because I can use them to fetch RGBD images in your ROS version .
        Thanks!

**Comment by saierd** [comment] 2021-04-06 06:25
From a first glance, your call of the `RenderPointMap` command looks correct, but it seems like it did not pick up the mono serial in the `Camera` parameter.

Can you please check that `self.mono_serial` contains the correct value and the parameter node contains the expected values before running the `execute()` line?

**Comment by ghx0x0** [comment] 2021-04-09 03:18
> From a first glance, your call of the `RenderPointMap` command looks correct, but it seems like it did not pick up the mono serial in the `Camera` parameter.
> 
> Can you please check that `self.mono_serial` contains the correct value and the parameter node contains the expected values before running the `execute()` line?

hello, saierd,
 I confirm that the value self.mono_serial contains the correct value, as I can grab a mono image successfully with this value in the same python code. 
 And can you tell me how to check the 'parameter node contains the expected values before running the execute() line?'   I cann't find a path in NxLibItem API to fetch the NxLibCommand params.

**Comment by saierd** [comment] 2021-04-09 05:50
You can use

```python
capture.parameters().as_json()
```

to get the parameter node as json.

**Comment by ghx0x0** [comment] 2021-04-09 05:56
> You can use
> 
> ```python
> capture.parameters().as_json()
> ```
> 
> to get the parameter node as json.

Thank you. I'll try it.

**Comment by ghx0x0** [comment] 2021-04-12 05:20
hi, saired,
     First,  I've test the params before execute, all the params seems right. Figures shows the params results and the code below:
           
![ensenso_444](https://user-images.githubusercontent.com/9670915/114343524-a291eb80-9b90-11eb-9902-1ec33176b8cd.png)
![ensenso_555](https://user-images.githubusercontent.com/9670915/114343533-a7ef3600-9b90-11eb-8f84-5cb09a757a66.png)

In order to filter the effect from  other Ensenso cameras, the network only contains 1 mono camera and 1 stereo camera, the NxView shows like this:
            
![ensenso_333](https://user-images.githubusercontent.com/9670915/114343561-b3426180-9b90-11eb-9fd8-968f7515a34d.png)

Second, another strange thing is that, the color images from [render point map texture] node looks like a gray image(see the 1st image in this topic). So I print its  pixel values and found that all the 4 channel values are same.  
         
![ensenso_666](https://user-images.githubusercontent.com/9670915/114343578-bb020600-9b90-11eb-81ce-f7622ac06833.png)
![eeee](https://user-images.githubusercontent.com/9670915/114343587-bdfcf680-9b90-11eb-8bf3-2c1940a189af.jpg)

Third,  the wrong color and depth images looks that they have just the 1/4 size of the original image(see the 1st and 2nd image in this topic),  does it has any relations with the Encoding/Decoding ? Because I found that in the ros version, it fetch the BinaryDataInfo first todo something about the decoding:
![ensenso_777](https://user-images.githubusercontent.com/9670915/114344142-dfaaad80-9b91-11eb-96fd-c55e31ee16cc.png)


Thank you so much.

**Comment by saierd** [comment] 2021-04-12 08:04
> Second, another strange thing is that, the color images from [render point map texture] node looks like a gray image(see the 1st image in this topic). So I print its pixel values and found that all the 4 channel values are same.

Yes, the problem seems to be that the command does not pick up the mono camera parameter. The default operation mode is to do a telecentric projection and using the stereo camera image as a texture (which is gray).

> Third, the wrong color and depth images looks that they have just the 1/4 size of the original image(see the 1st and 2nd image in this topic), does it has any relations with the Encoding/Decoding ? Because I found that in the ros version, it fetch the BinaryDataInfo first todo something about the decoding:

This is again the same problem as above, because for the telecentric operation mode, you can specify the target resolution yourself. In this case, you simply get the default resolution (which is independent from the camera). You don't have to do the steps from the ROS code, because `get_binary_data()` does it for you (see the code [here](https://github.com/ensenso/nxlib-python-interface/blob/0c0082d17939efd194450c527e12f8d9e0ffd8da/ensenso_nxlib/item.py#L175)).

---

I currently don't know what the problem is. As far as I can see, everything you sent so far looks fine and should either work or give you an error message if you don't satisfy the preconditions.

I just put together a simple example, which works for me. Can you start from this code and check if it gives the expected result for you?

```python
from ensenso_nxlib import NxLibCommand, NxLibItem
from ensenso_nxlib.constants import *
import ensenso_nxlib

stereo_serial = "..."
mono_serial = "..."

ensenso_nxlib.api.initialize()

cmd = NxLibCommand(CMD_OPEN)
cmd.parameters()[ITM_CAMERAS][0] = stereo_serial
cmd.parameters()[ITM_CAMERAS][1] = mono_serial
cmd.execute()

NxLibCommand(CMD_CAPTURE).execute()
NxLibCommand(CMD_COMPUTE_DISPARITY_MAP).execute()
NxLibCommand(CMD_COMPUTE_POINT_MAP).execute()

cmd = NxLibCommand(CMD_RENDER_POINT_MAP)
cmd.parameters()[ITM_CAMERA] = mono_serial
cmd.parameters()[ITM_NEAR] = 100
cmd.parameters()[ITM_FAR] = 5000
cmd.execute()

cmd = NxLibCommand(CMD_SAVE_IMAGE)
cmd.parameters()[ITM_NODE] = NxLibItem()[ITM_IMAGES][ITM_RENDER_POINT_MAP_TEXTURE].path
cmd.parameters()[ITM_FILENAME] = "color.png"
cmd.execute()
cmd.parameters()[ITM_NODE] = NxLibItem()[ITM_IMAGES][ITM_RENDER_POINT_MAP].path
cmd.parameters()[ITM_FILENAME] = "depth.png"
cmd.execute()
```

**Comment by ghx0x0** [comment] 2021-04-13 03:01
hi, saired,

Something wierd.
Using your code, I got the following images below and it seems that the rendered color size is right except all pixels RGB are black.
The image got by nxView also list below.  （from top to bottom:  rendered color, rendered depth, nxView color）
![test_color](https://user-images.githubusercontent.com/9670915/114489734-35d92880-9c46-11eb-8032-7a50f006ce84.png)
![test_depth](https://user-images.githubusercontent.com/9670915/114489754-42f61780-9c46-11eb-9fe4-66ec5a83207a.png)
![13262754885777_4103356480](https://user-images.githubusercontent.com/9670915/114489760-47223500-9c46-11eb-9154-4a832dbbee5a.png)

Then I load the camera params file and try again. The rendered color image finally has color pixels and its size is also right, but it only rendered 1/4 size, and the rendered depth is still 1/4 size.
Code and images list below.
![test_color (复件)](https://user-images.githubusercontent.com/9670915/114489850-67ea8a80-9c46-11eb-8186-f8ccaeedd652.png)
![test_depth (复件)](https://user-images.githubusercontent.com/9670915/114489858-6b7e1180-9c46-11eb-986d-67a80f8bd36c.png)

```
from ensenso_nxlib import NxLibCommand, NxLibItem
from ensenso_nxlib.constants import *
import ensenso_nxlib

stereo_serial = "182235"
mono_serial = "4103356480"

ensenso_nxlib.api.initialize()

cmd = NxLibCommand(CMD_OPEN)
cmd.parameters()[ITM_CAMERAS][0] = stereo_serial
cmd.parameters()[ITM_CAMERAS][1] = mono_serial
cmd.execute()


stero_cam = NxLibItem()[ITM_CAMERAS][stereo_serial]
param = json.dumps(json.load(open('right_stereo_params.json', "r")))
stero_cam << param
print('Load the stereo Camera parameter file....')

mono_cam = NxLibItem()[ITM_CAMERAS][mono_serial]
param = json.dumps(json.load(open('right_mono_params.json', "r")))
mono_cam << param
print('Load the  mono  Camera parameter file....')


NxLibCommand(CMD_CAPTURE).execute()
NxLibCommand(CMD_COMPUTE_DISPARITY_MAP).execute()
NxLibCommand(CMD_COMPUTE_POINT_MAP).execute()

cmd = NxLibCommand(CMD_RENDER_POINT_MAP)
cmd.parameters()[ITM_CAMERA] = mono_serial
cmd.parameters()[ITM_NEAR] = 100
cmd.parameters()[ITM_FAR] = 5000
cmd.execute()

cmd = NxLibCommand(CMD_SAVE_IMAGE)
cmd.parameters()[ITM_NODE] = NxLibItem()[ITM_IMAGES][ITM_RENDER_POINT_MAP_TEXTURE].path
cmd.parameters()[ITM_FILENAME] = "test_color.png"
cmd.execute()
cmd.parameters()[ITM_NODE] = NxLibItem()[ITM_IMAGES][ITM_RENDER_POINT_MAP].path
cmd.parameters()[ITM_FILENAME] = "test_depth.png"
cmd.execute()
```

So currently, there are 2 questions:
1. do you know the reason why the color image are black without loading the params file?
2. why the rendered depth resize to 1/4 size of a normal image? Is there anything wrong in the stereo params file?

By the way, do you know how to set the default params except loading files explicitly ? I want to try in other ways.

I upload my params files, if you need it, just replace the '.txt' with '.json'.
[right_mono_params.txt](https://github.com/ensenso/nxlib-python-interface/files/6300972/right_mono_params.txt)
[right_stereo_params.txt](https://github.com/ensenso/nxlib-python-interface/files/6300973/right_stereo_params.txt)


Thank you.

**Comment by ghx0x0** [comment] 2021-04-13 03:58
hi, saired,

Problem solved.
I reconfigure the 2 cameras and found that it is the mono camera's file cause the rendered images to size 1/4.
The following 2 mono cameras params file, the 1st one works fine and the 2nd one will reproduce the '1/4 rendered' problem.

[mono.txt](https://github.com/ensenso/nxlib-python-interface/files/6301111/mono.txt)
[mono_binning2.txt](https://github.com/ensenso/nxlib-python-interface/files/6301112/mono_binning2.txt)

The only difference is that, in the mono_Binning2.txt, the Binning parameters equals to 2, which will cause the camera's intrics focal length change to 0.5x.

If you have a X-series camera, you can use the above two mono files and the following  stereo file to test:
[stereo.txt](https://github.com/ensenso/nxlib-python-interface/files/6301129/stereo.txt)
 
The problem only exists in python code, if you load the files in nxView, the nxView always works fine no matter what Binning parameters you set.

**Comment by saierd** [comment] 2021-04-13 10:16
Very nice if it works for you now.

>     1. do you know the reason why the color image are black without loading the params file?

I guess that is because your mono camera has quite a high exposure time. With the default settings (5ms exposure time) the image will be almost black and it will take a few frames to adapt.

>     2. why the rendered depth resize to 1/4 size of a normal image? Is there anything wrong in the stereo params file?

This is expected if the mono camera has binning enabled. RenderPointMap will render so that the result lines up with the mono camera's "rectified" (undistorted) image. Enabling binning effectively reduces the resolution of the mono camera and therefore the RenderPointMap image will also become smaller.

I will close this issue for now. Feel free to reopen if you have further questions.

**Closed as completed by saierd** 2021-04-13 10:16 UTC
